# Generated by Django 3.2.9 on 2021-12-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email address')),
                ('username', models.CharField(max_length=70, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='phone number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date_Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customer_img/%y')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('customer_address', models.TextField(max_length=70, verbose_name='Customer Address')),
                ('gst_number', models.IntegerField(verbose_name='GST Number')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='Customer Phone No.')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_img/%y')),
                ('product_name', models.CharField(max_length=300, verbose_name='Product name')),
                ('product_barcode', models.IntegerField(verbose_name='Product barcode')),
                ('product_color', models.CharField(max_length=300, verbose_name='Product color')),
                ('product_size', models.IntegerField(verbose_name='Product size')),
                ('product_discription', models.TextField(max_length=100, verbose_name='Product discription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_img/%y')),
                ('vendor_name', models.CharField(max_length=300, verbose_name='Vendor name')),
                ('company_name', models.CharField(max_length=300, verbose_name='Company name')),
                ('vendor_address', models.TextField(max_length=100, verbose_name='Vendor address')),
                ('gst_number', models.IntegerField(verbose_name='GST Number')),
                ('vendor_phone', models.CharField(max_length=11, verbose_name='Vendor phone')),
                ('vendor_email', models.EmailField(max_length=254, verbose_name='Vendor email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('business_email', models.EmailField(max_length=250)),
                ('business_phone', models.CharField(max_length=11)),
                ('business_website', models.CharField(max_length=500)),
                ('business_address', models.TextField()),
                ('type_of_entity', models.CharField(choices=[('Individual', 'Individula'), ('Partnership', 'Partnership'), ('Public and Private Limited', 'Public and Private Limited'), ('Trust/Societies', 'Trust/Societies'), ('LLP', 'LLP'), ('Others', 'Others'), ('Unregistered Business', 'Unregistered Business')], max_length=200)),
                ('industry_type', models.CharField(choices=[('Textile', 'Textile'), ('Manufacturing', 'Manufacturing'), ('Banking/Finance Services', 'Banking/Finance Services'), ('Telecom/Telecom Equipments', 'Telecom/Telecom Equipments'), ('Export/Import', 'Export/Import'), ('Hospitality', 'Hospitality'), ('Construction', 'Construction'), ('Broker', 'Broker'), ('IT/ITes', 'IT/ITes'), ('Defence', 'Defence'), ('Cement', 'Cement'), ('Shopping', 'Shopping'), ('Retailling', 'Retailling'), ('Real Estate', 'Real Estate'), ('Airport', 'Airport'), ('Sugar', 'Sugar'), ('Tea', 'Tea'), ('Paper Product', 'Paper Product'), ('Rubber Product', 'Rubber Product'), ('Coal', 'Coal'), ('NBFC', 'NBFC'), ('Computer software', 'Computer software'), ('Hardware', 'Hardware'), ('Doctors', 'Doctors'), ('Agriculter', 'Agriculter'), ('Automobile', 'Automobile'), ('Furnitures', 'Furnitures'), ('Marketing', 'Marketing'), ('Water Supply', 'Water Supply')], max_length=200)),
                ('business_type', models.CharField(choices=[('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer'), ('Services', 'Services'), ('Others', 'Others')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.IntegerField(verbose_name='Sales quantity')),
                ('gst_number', models.IntegerField(verbose_name='GST Number')),
                ('sales_date', models.DateField(verbose_name='Sales date')),
                ('sales_price', models.IntegerField(verbose_name='Sales price')),
                ('sales_type', models.CharField(choices=[('Debit', 'Debit'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], max_length=100, verbose_name='Sales type')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoc.customerdetailmodel')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoc.productlistmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.IntegerField(verbose_name='Purchase quantity')),
                ('gst_number', models.IntegerField(verbose_name='GST Number')),
                ('purchase_date', models.DateField(verbose_name='Purchase date')),
                ('purchase_price', models.FloatField(verbose_name='Purchase price')),
                ('purchase_type', models.CharField(choices=[('Debit', 'Debit'), ('Cheque', 'Cheque'), ('Cash', 'Cash')], max_length=100, verbose_name='Purchase type')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoc.productlistmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoc.vendordetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profileimg/%y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpansesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanses_title', models.CharField(max_length=50, verbose_name='Expenses Title')),
                ('expanses_discription', models.TextField(max_length=150, verbose_name='Expenses Discription')),
                ('expanses_date', models.DateField(verbose_name='Expenses Date')),
                ('expanses_amount', models.IntegerField(verbose_name='Expenses Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
